#!/usr/bin/env python
# -*- coding: UTF-8 -*- 
'''
@author: zhujin
'''

import ssl
import urllib2
import argparse


def tlscheck(url):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    
    try:
        response = urllib2.urlopen(url, context=ctx)
        print(response.code)
        print('yes, nginx spport tls1.2')
    except urllib2.URLError, e:
        raise e
        

def main():
	parser = argparse.ArgumentParser()
	parser.add_argument('-url',action="store",dest='url',help="url, exmple: https://www.test.com")
    
	args = parser.parse_args()
	url = args.url
    if url:
        tlscheck(url)
    else:
        print('Usage: ./tlscheck -url url, exmple: ./tlscheck -url https://www.test.com')
            
        
if __name__ == '__main__':
    main()
    